# name: ci

# on: [push, pull_request]

# jobs:
#   build:
#     strategy:
#       matrix:
#         env:
#           - {ROS_DISTRO: noetic, ROS_REPO: testing}
#           - {ROS_DISTRO: noetic, ROS_REPO: main}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: 'ros-industrial/industrial_ci@master'
#         run: |
#           git --version
#         env: ${{matrix.env}}

name: docker_ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        # uses: docker/bake-action@v6
        uses: docker/build-push-action@v6
        with:
          file: "./docker/Dockerfile"
          push: false
          # set: |
          #   *.tags=user/app:latest

  integration_test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and run integration tests
        run: docker compose -f docker/docker-compose.yaml --profile test up --build --exit-code-from test test
